services:
  - type: web
    name: ssn-hall-booking
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python seed_data.py && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: ssn-hall-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: ssn-hall-db
    databaseName: seminar_hall_db
    user: ssn_user
    plan: free
